### PR TITLE
Only rerender if dimensions changed

### PR DESCRIPTION
**Pull request by nxz91**

### CODE REVIEW

**Comment by ZeeCoder** [comment]
Good start, I think I'll also add a precision option to this, so that you can further decrease improve rendering.
The native resize observer responds with subpixel values, which means a render is triggered pretty much all the time.
Related: #19

**Comment by nxz91** [comment]
Good point :) added a commit.

**Comment by ZeeCoder** [comment]
I don't think `.toPrecision` works the way you think it does:
```js
123.456.toPrecision(2); // => '1.2e+2'
123.456.toPrecision(3); // => 123
123.456.toPrecision(4); // => 123.5
123.456.toPrecision(5); // => 123.46
```
☝ Not too useful 

I think it's better to just `Math.floor` the values for consistency.
I doubt anyone needs subpixel values anyway, and if so, we can always add real precision support later as a new feature. 🤷‍♂️

**Comment by ZeeCoder** [comment]
Also, since you don't have width, and height in your effect deps, it won't have a fresh value to compare the new one to.

**Comment by ZeeCoder** [comment]
I've implemented the changes I had in mind in the next channel if you want to give it a go.
Demo:
https://codesandbox.io/s/vigilant-wave-buftd

**Comment by nxz91** [comment]
Oops! Awesome, thanks!

**Pull request closed without merging**
